nodes:
  - id: cdse_key
    ref: inputs.cdse_key
  - id: cdse_secret
    ref: inputs.cdse_secret
  - id: earth_data_hub_key
    ref: inputs.earth_data_hub_key
  - id: bbox
    ref: inputs.bbox
  - id: fraction_sampled
    ref: inputs.fraction_sampled
  - id: point_cloud_generator
    ref: models.point_cloud_generator
  - id: output_point_cloud
    ref: outputs.point_cloud
  - id: output_mesh
    ref: outputs.mesh 
edges:
  - from:   
      id: cdse_key
    to:
      id: point_cloud_generator
      port: cdse_key
  - from: 
      id: cdse_secret
    to: 
      id: point_cloud_generator
      port: cdse_secret
  - from:
      id: earth_data_hub_key
    to:
      id: point_cloud_generator
      port: earth_data_hub_key
  - from: 
      id: bbox
    to:
      id: point_cloud_generator
      port: bbox
  - from:
      id: fraction_sampled
    to: 
      id: point_cloud_generator
      port: fraction_sampled
  - from:
      id: point_cloud_generator
      port: out_point_cloud
    to:
      id: output_point_cloud
  - from: 
      id: point_cloud_generator
      port: out_mesh
    to: 
      id: output_mesh
 