nodes:
  - id: cdse_key
    ref: inputs.cdse_key
  - id: cdse_secret
    ref: inputs.cdse_secret
  - id: earth_data_hub_key
    ref: inputs.earth_data_hub_key
  - id: bbox
    ref: inputs.bbox
  - id: sampled_fraction
    ref: inputs.sampled_fraction
  - id: point_cloud_generator
    ref: models.point_cloud_generator
  - id: output_point_cloud
    ref: outputs.out
edges:
  - from:   
      id: cdse_key
    to:
      id: point_cloud_generator
      port: cdse_key
  - from: 
      id: cdse_secret
    to: 
      id: point_cloud_generator
      port: cdse_secret
  - from:
      id: earth_data_hub_key
    to:
      id: point_cloud_generator
      port: earth_data_hub_key
  - from: 
      id: bbox
    to:
      id: point_cloud_generator
      port: bbox
  - from:
      id: sampled_fraction
    to: 
      id: point_cloud_generator
      port: sampled_fraction
  - from:
      id: point_cloud_generator
      port: out_point_cloud
    to:
      id: output_point_cloud
 